name: Build Multi-Arch Docker Image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

env:
  # Image name
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/postgres16-rdkit

jobs:
  # Build AMD64
  build-amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (AMD64)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-amd64
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }}-amd64
          build-args: |
            CACHEBUST=${{ env.RELEASE_DATE }}
          cache-from: type=gha,scope=amd64
          cache-to: type=gha,mode=max,scope=amd64

  # Build ARM64
  # ==================================================
  build-arm64:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push (ARM64)
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-arm64
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }}-arm64
          build-args: |
            CACHEBUST=${{ env.RELEASE_DATE }}
          cache-from: type=gha,scope=arm64
          cache-to: type=gha,mode=max,scope=arm64

  # Merge manifests
  merge-manifests:
    runs-on: ubuntu-latest
    needs: [build-amd64, build-arm64]
    steps:
      - name: Set release date
        run: echo "RELEASE_DATE=$(date +%Y.%m.%d)" >> ${GITHUB_ENV}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Manifest List
        run: |
          # 1. create "latest" (contains both architectures)
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:latest \
            ${{ env.IMAGE_NAME }}:latest-amd64 \
            ${{ env.IMAGE_NAME }}:latest-arm64
          
          # 2. create "release date" (contains both architectures)
          docker buildx imagetools create -t ${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }} \
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }}-amd64 \
            ${{ env.IMAGE_NAME }}:${{ env.RELEASE_DATE }}-arm64

      - name: Verify
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE_NAME }}:latest
